services:
  nickstats-api:
    build: .
    container_name: nickstats-api
    restart: unless-stopped
    env_file: .env
    expose:
      - "8000"
    networks:
      - web
      - mysql

networks:
  web:
    name: web_default
    external: true
  mysql:
    name: mysql_default
    external: true
